import type { EditorialArticle, EditorialBrief } from "@/features/editorial/types";

export const editorialArticlesFixture: readonly EditorialArticle[] = [
  {
    id: "article-1",
    title: "Como participar de licitação: guia prático para empresas",
    slug: "como-participar-de-licitacao",
    category: "Começar em licitações",
    cluster: "Participar de licitações",
    primaryKeyword: "como participar de licitação",
    searchIntent: "informational",
    status: "published",
    updatedAt: "31 ago. 2026",
    owner: "Conteúdo LicitaBase",
    seoScore: 96,
  },
  {
    id: "article-2",
    title: "Documentos necessários para participar de uma licitação",
    slug: "documentos-necessarios-para-licitacao",
    category: "Documentação",
    cluster: "Participar de licitações",
    primaryKeyword: "documentos para licitação",
    searchIntent: "informational",
    status: "published",
    updatedAt: "31 ago. 2026",
    owner: "Conteúdo LicitaBase",
    seoScore: 94,
  },
  {
    id: "article-3",
    title: "Como analisar edital antes de enviar uma proposta",
    slug: "como-analisar-edital-antes-da-proposta",
    category: "Análise de edital",
    cluster: "Participar de licitações",
    primaryKeyword: "como analisar edital de licitação",
    searchIntent: "informational",
    status: "in_review",
    updatedAt: "16 set. 2026",
    owner: "Marina · revisão jurídica",
    seoScore: 82,
  },
  {
    id: "article-4",
    title: "Como organizar uma rotina de monitoramento de editais",
    slug: "rotina-monitoramento-editais",
    category: "Encontrar oportunidades",
    cluster: "Encontrar oportunidades",
    primaryKeyword: "monitoramento de editais",
    searchIntent: "commercial",
    status: "draft",
    updatedAt: "16 set. 2026",
    owner: "Rascunho assistido",
    seoScore: 61,
  },
  {
    id: "article-5",
    title: "Como montar proposta de preços para licitação",
    slug: "como-montar-proposta-precos-licitacao",
    category: "Proposta comercial",
    cluster: "Participar de licitações",
    primaryKeyword: "proposta de preços para licitação",
    searchIntent: "informational",
    status: "scheduled",
    updatedAt: "15 set. 2026",
    owner: "Conteúdo LicitaBase",
    seoScore: 92,
    scheduledFor: "22 set. 2026 · 09:00",
  },
];

export const emptyBriefFixture: EditorialBrief = {
  topic: "Como uma empresa avalia se vale a pena participar de uma licitação",
  primaryKeyword: "vale a pena participar de licitação",
  secondaryKeywords: "análise de edital, aderência da oportunidade, proposta comercial",
  searchIntent: "informational",
  audience: "Gestores comerciais e equipes que começam a operar licitações públicas.",
  internalLinks: "Como participar de licitação; Como ler um edital de licitação",
  sourceRequirements: "Usar apenas fontes oficiais quando mencionar regras, prazos ou documentos.",
  callToAction: "Conheça como a LicitaBase ajuda a analisar oportunidades antes da proposta.",
};
