/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotLancesRouteImport } from './routes/bot-lances'
import { Route as Dash2RouteImport } from './routes/dash2'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LpRouteImport } from './routes/lp'
import { Route as BotLancesIndexRouteImport } from './routes/bot-lances.index'
import { Route as BotLancesConfiguracoesRouteImport } from './routes/bot-lances.configuracoes'
import { Route as BotLancesHistoricoRouteImport } from './routes/bot-lances.historico'
import { Route as BotLancesMonitoramentoRouteImport } from './routes/bot-lances.monitoramento'
import { Route as BotLancesRelatoriosRouteImport } from './routes/bot-lances.relatorios'
import { Route as PlanosCompararRouteImport } from './routes/planos.comparar'
import { Route as BotLancesDisputasIndexRouteImport } from './routes/bot-lances.disputas.index'
import { Route as BotLancesDisputasDisputeIdRouteImport } from './routes/bot-lances.disputas.$disputeId'
import { Route as Dash2LicitacoesBuscarRouteImport } from './routes/dash2.licitacoes.buscar'
import { Route as Dash2OportunidadesNovasRouteImport } from './routes/dash2.oportunidades.novas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotLancesRoute = BotLancesRouteImport.update({
  id: '/bot-lances',
  path: '/bot-lances',
  getParentRoute: () => rootRouteImport,
} as any)
const Dash2Route = Dash2RouteImport.update({
  id: '/dash2',
  path: '/dash2',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LpRoute = LpRouteImport.update({
  id: '/lp',
  path: '/lp',
  getParentRoute: () => rootRouteImport,
} as any)
const BotLancesIndexRoute = BotLancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BotLancesRoute,
} as any)
const BotLancesConfiguracoesRoute = BotLancesConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => BotLancesRoute,
} as any)
const BotLancesHistoricoRoute = BotLancesHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => BotLancesRoute,
} as any)
const BotLancesMonitoramentoRoute = BotLancesMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => BotLancesRoute,
} as any)
const BotLancesRelatoriosRoute = BotLancesRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => BotLancesRoute,
} as any)
const PlanosCompararRoute = PlanosCompararRouteImport.update({
  id: '/planos/comparar',
  path: '/planos/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const BotLancesDisputasIndexRoute = BotLancesDisputasIndexRouteImport.update({
  id: '/disputas/',
  path: '/disputas/',
  getParentRoute: () => BotLancesRoute,
} as any)
const BotLancesDisputasDisputeIdRoute =
  BotLancesDisputasDisputeIdRouteImport.update({
    id: '/disputas/$disputeId',
    path: '/disputas/$disputeId',
    getParentRoute: () => BotLancesRoute,
  } as any)
const Dash2LicitacoesBuscarRoute = Dash2LicitacoesBuscarRouteImport.update({
  id: '/licitacoes/buscar',
  path: '/licitacoes/buscar',
  getParentRoute: () => Dash2Route,
} as any)
const Dash2OportunidadesNovasRoute = Dash2OportunidadesNovasRouteImport.update({
  id: '/oportunidades/novas',
  path: '/oportunidades/novas',
  getParentRoute: () => Dash2Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bot-lances': typeof BotLancesRouteWithChildren
  '/dash2': typeof Dash2RouteWithChildren
  '/login': typeof LoginRoute
  '/lp': typeof LpRoute
  '/bot-lances/configuracoes': typeof BotLancesConfiguracoesRoute
  '/bot-lances/historico': typeof BotLancesHistoricoRoute
  '/bot-lances/monitoramento': typeof BotLancesMonitoramentoRoute
  '/bot-lances/relatorios': typeof BotLancesRelatoriosRoute
  '/planos/comparar': typeof PlanosCompararRoute
  '/bot-lances/': typeof BotLancesIndexRoute
  '/bot-lances/disputas/$disputeId': typeof BotLancesDisputasDisputeIdRoute
  '/dash2/licitacoes/buscar': typeof Dash2LicitacoesBuscarRoute
  '/dash2/oportunidades/novas': typeof Dash2OportunidadesNovasRoute
  '/bot-lances/disputas/': typeof BotLancesDisputasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dash2': typeof Dash2RouteWithChildren
  '/login': typeof LoginRoute
  '/lp': typeof LpRoute
  '/bot-lances/configuracoes': typeof BotLancesConfiguracoesRoute
  '/bot-lances/historico': typeof BotLancesHistoricoRoute
  '/bot-lances/monitoramento': typeof BotLancesMonitoramentoRoute
  '/bot-lances/relatorios': typeof BotLancesRelatoriosRoute
  '/planos/comparar': typeof PlanosCompararRoute
  '/bot-lances': typeof BotLancesIndexRoute
  '/bot-lances/disputas/$disputeId': typeof BotLancesDisputasDisputeIdRoute
  '/dash2/licitacoes/buscar': typeof Dash2LicitacoesBuscarRoute
  '/dash2/oportunidades/novas': typeof Dash2OportunidadesNovasRoute
  '/bot-lances/disputas': typeof BotLancesDisputasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bot-lances': typeof BotLancesRouteWithChildren
  '/dash2': typeof Dash2RouteWithChildren
  '/login': typeof LoginRoute
  '/lp': typeof LpRoute
  '/bot-lances/configuracoes': typeof BotLancesConfiguracoesRoute
  '/bot-lances/historico': typeof BotLancesHistoricoRoute
  '/bot-lances/monitoramento': typeof BotLancesMonitoramentoRoute
  '/bot-lances/relatorios': typeof BotLancesRelatoriosRoute
  '/planos/comparar': typeof PlanosCompararRoute
  '/bot-lances/': typeof BotLancesIndexRoute
  '/bot-lances/disputas/$disputeId': typeof BotLancesDisputasDisputeIdRoute
  '/dash2/licitacoes/buscar': typeof Dash2LicitacoesBuscarRoute
  '/dash2/oportunidades/novas': typeof Dash2OportunidadesNovasRoute
  '/bot-lances/disputas/': typeof BotLancesDisputasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bot-lances'
    | '/dash2'
    | '/login'
    | '/lp'
    | '/bot-lances/configuracoes'
    | '/bot-lances/historico'
    | '/bot-lances/monitoramento'
    | '/bot-lances/relatorios'
    | '/planos/comparar'
    | '/bot-lances/'
    | '/bot-lances/disputas/$disputeId'
    | '/dash2/licitacoes/buscar'
    | '/dash2/oportunidades/novas'
    | '/bot-lances/disputas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dash2'
    | '/login'
    | '/lp'
    | '/bot-lances/configuracoes'
    | '/bot-lances/historico'
    | '/bot-lances/monitoramento'
    | '/bot-lances/relatorios'
    | '/planos/comparar'
    | '/bot-lances'
    | '/bot-lances/disputas/$disputeId'
    | '/dash2/licitacoes/buscar'
    | '/dash2/oportunidades/novas'
    | '/bot-lances/disputas'
  id:
    | '__root__'
    | '/'
    | '/bot-lances'
    | '/dash2'
    | '/login'
    | '/lp'
    | '/bot-lances/configuracoes'
    | '/bot-lances/historico'
    | '/bot-lances/monitoramento'
    | '/bot-lances/relatorios'
    | '/planos/comparar'
    | '/bot-lances/'
    | '/bot-lances/disputas/$disputeId'
    | '/dash2/licitacoes/buscar'
    | '/dash2/oportunidades/novas'
    | '/bot-lances/disputas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotLancesRoute: typeof BotLancesRouteWithChildren
  Dash2Route: typeof Dash2RouteWithChildren
  LoginRoute: typeof LoginRoute
  LpRoute: typeof LpRoute
  PlanosCompararRoute: typeof PlanosCompararRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-lances': {
      id: '/bot-lances'
      path: '/bot-lances'
      fullPath: '/bot-lances'
      preLoaderRoute: typeof BotLancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash2': {
      id: '/dash2'
      path: '/dash2'
      fullPath: '/dash2'
      preLoaderRoute: typeof Dash2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp': {
      id: '/lp'
      path: '/lp'
      fullPath: '/lp'
      preLoaderRoute: typeof LpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-lances/': {
      id: '/bot-lances/'
      path: '/'
      fullPath: '/bot-lances/'
      preLoaderRoute: typeof BotLancesIndexRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/bot-lances/configuracoes': {
      id: '/bot-lances/configuracoes'
      path: '/configuracoes'
      fullPath: '/bot-lances/configuracoes'
      preLoaderRoute: typeof BotLancesConfiguracoesRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/bot-lances/historico': {
      id: '/bot-lances/historico'
      path: '/historico'
      fullPath: '/bot-lances/historico'
      preLoaderRoute: typeof BotLancesHistoricoRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/bot-lances/monitoramento': {
      id: '/bot-lances/monitoramento'
      path: '/monitoramento'
      fullPath: '/bot-lances/monitoramento'
      preLoaderRoute: typeof BotLancesMonitoramentoRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/bot-lances/relatorios': {
      id: '/bot-lances/relatorios'
      path: '/relatorios'
      fullPath: '/bot-lances/relatorios'
      preLoaderRoute: typeof BotLancesRelatoriosRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/planos/comparar': {
      id: '/planos/comparar'
      path: '/planos/comparar'
      fullPath: '/planos/comparar'
      preLoaderRoute: typeof PlanosCompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-lances/disputas/': {
      id: '/bot-lances/disputas/'
      path: '/disputas'
      fullPath: '/bot-lances/disputas/'
      preLoaderRoute: typeof BotLancesDisputasIndexRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/bot-lances/disputas/$disputeId': {
      id: '/bot-lances/disputas/$disputeId'
      path: '/disputas/$disputeId'
      fullPath: '/bot-lances/disputas/$disputeId'
      preLoaderRoute: typeof BotLancesDisputasDisputeIdRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/dash2/licitacoes/buscar': {
      id: '/dash2/licitacoes/buscar'
      path: '/licitacoes/buscar'
      fullPath: '/dash2/licitacoes/buscar'
      preLoaderRoute: typeof Dash2LicitacoesBuscarRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/oportunidades/novas': {
      id: '/dash2/oportunidades/novas'
      path: '/oportunidades/novas'
      fullPath: '/dash2/oportunidades/novas'
      preLoaderRoute: typeof Dash2OportunidadesNovasRouteImport
      parentRoute: typeof Dash2Route
    }
  }
}

interface BotLancesRouteChildren {
  BotLancesConfiguracoesRoute: typeof BotLancesConfiguracoesRoute
  BotLancesHistoricoRoute: typeof BotLancesHistoricoRoute
  BotLancesMonitoramentoRoute: typeof BotLancesMonitoramentoRoute
  BotLancesRelatoriosRoute: typeof BotLancesRelatoriosRoute
  BotLancesIndexRoute: typeof BotLancesIndexRoute
  BotLancesDisputasDisputeIdRoute: typeof BotLancesDisputasDisputeIdRoute
  BotLancesDisputasIndexRoute: typeof BotLancesDisputasIndexRoute
}

const BotLancesRouteChildren: BotLancesRouteChildren = {
  BotLancesConfiguracoesRoute: BotLancesConfiguracoesRoute,
  BotLancesHistoricoRoute: BotLancesHistoricoRoute,
  BotLancesMonitoramentoRoute: BotLancesMonitoramentoRoute,
  BotLancesRelatoriosRoute: BotLancesRelatoriosRoute,
  BotLancesIndexRoute: BotLancesIndexRoute,
  BotLancesDisputasDisputeIdRoute: BotLancesDisputasDisputeIdRoute,
  BotLancesDisputasIndexRoute: BotLancesDisputasIndexRoute,
}

const BotLancesRouteWithChildren = BotLancesRoute._addFileChildren(
  BotLancesRouteChildren,
)

interface Dash2RouteChildren {
  Dash2LicitacoesBuscarRoute: typeof Dash2LicitacoesBuscarRoute
  Dash2OportunidadesNovasRoute: typeof Dash2OportunidadesNovasRoute
}

const Dash2RouteChildren: Dash2RouteChildren = {
  Dash2LicitacoesBuscarRoute: Dash2LicitacoesBuscarRoute,
  Dash2OportunidadesNovasRoute: Dash2OportunidadesNovasRoute,
}

const Dash2RouteWithChildren = Dash2Route._addFileChildren(Dash2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotLancesRoute: BotLancesRouteWithChildren,
  Dash2Route: Dash2RouteWithChildren,
  LoginRoute: LoginRoute,
  LpRoute: LpRoute,
  PlanosCompararRoute: PlanosCompararRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
