/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotLancesRouteImport } from './routes/bot-lances'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as ConcorrentesRouteImport } from './routes/concorrentes'
import { Route as Dash2RouteImport } from './routes/dash2'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as ItensRouteImport } from './routes/itens'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LpRouteImport } from './routes/lp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as RaioXRouteImport } from './routes/raio-x'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ScoreOrgaosRouteImport } from './routes/score-orgaos'
import { Route as BotLancesIndexRouteImport } from './routes/bot-lances.index'
import { Route as BotLancesConfiguracoesRouteImport } from './routes/bot-lances.configuracoes'
import { Route as BotLancesHistoricoRouteImport } from './routes/bot-lances.historico'
import { Route as BotLancesMonitoramentoRouteImport } from './routes/bot-lances.monitoramento'
import { Route as BotLancesRelatoriosRouteImport } from './routes/bot-lances.relatorios'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as CategoriasCategoryIdRouteImport } from './routes/categorias.$categoryId'
import { Route as ConcorrentesIndexRouteImport } from './routes/concorrentes.index'
import { Route as ConcorrentesCategoryIdRouteImport } from './routes/concorrentes.$categoryId'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as Dash2AjudaRouteImport } from './routes/dash2.ajuda'
import { Route as PlanosCompararRouteImport } from './routes/planos.comparar'
import { Route as BotLancesDisputasIndexRouteImport } from './routes/bot-lances.disputas.index'
import { Route as BotLancesDisputasDisputeIdRouteImport } from './routes/bot-lances.disputas.$disputeId'
import { Route as ConcorrentesCategoryIdCompanyIdRouteImport } from './routes/concorrentes.$categoryId.$companyId'
import { Route as Dash2ConfiguracoesEmpresaRouteImport } from './routes/dash2.configuracoes.empresa'
import { Route as Dash2ConfiguracoesEquipeRouteImport } from './routes/dash2.configuracoes.equipe'
import { Route as Dash2ConfiguracoesNotificacoesRouteImport } from './routes/dash2.configuracoes.notificacoes'
import { Route as Dash2ConfiguracoesPerfilRouteImport } from './routes/dash2.configuracoes.perfil'
import { Route as Dash2ConfiguracoesPlanoRouteImport } from './routes/dash2.configuracoes.plano'
import { Route as Dash2ConfiguracoesSegurancaRouteImport } from './routes/dash2.configuracoes.seguranca'
import { Route as Dash2GestaoTemplatesEmailsRouteImport } from './routes/dash2.gestao.templates-emails'
import { Route as Dash2LicitacoesLicitacaoIdRouteImport } from './routes/dash2.licitacoes.$licitacaoId'
import { Route as Dash2LicitacoesBuscarRouteImport } from './routes/dash2.licitacoes.buscar'
import { Route as Dash2LicitacoesFiltrosSalvosRouteImport } from './routes/dash2.licitacoes.filtros-salvos'
import { Route as Dash2OperacaoAnotacoesRouteImport } from './routes/dash2.operacao.anotacoes'
import { Route as Dash2OperacaoMinhasLicitacoesRouteImport } from './routes/dash2.operacao.minhas-licitacoes'
import { Route as Dash2OportunidadesFavoritosRouteImport } from './routes/dash2.oportunidades.favoritos'
import { Route as Dash2OportunidadesNovasRouteImport } from './routes/dash2.oportunidades.novas'
import { Route as CategoriasCategoryIdEstadoStateIdRouteImport } from './routes/categorias.$categoryId.estado.$stateId'
import { Route as Dash2ConfiguracoesFaturasInvoiceIdRouteImport } from './routes/dash2.configuracoes.faturas.$invoiceId'
import { Route as Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteImport } from './routes/dash2.operacao.minhas-licitacoes.$licitacaoId'
import { Route as Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRouteImport } from './routes/dash2.operacao.minhas-licitacoes.$licitacaoId.disputa'
import { Route as Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRouteImport } from './routes/dash2.operacao.minhas-licitacoes.$licitacaoId.proposta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotLancesRoute = BotLancesRouteImport.update({
  id: '/bot-lances',
  path: '/bot-lances',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcorrentesRoute = ConcorrentesRouteImport.update({
  id: '/concorrentes',
  path: '/concorrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const Dash2Route = Dash2RouteImport.update({
  id: '/dash2',
  path: '/dash2',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ItensRoute = ItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LpRoute = LpRouteImport.update({
  id: '/lp',
  path: '/lp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RaioXRoute = RaioXRouteImport.update({
  id: '/raio-x',
  path: '/raio-x',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreOrgaosRoute = ScoreOrgaosRouteImport.update({
  id: '/score-orgaos',
  path: '/score-orgaos',
  getParentRoute: () => rootRouteImport,
} as any)
const BotLancesIndexRoute = BotLancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BotLancesRoute,
} as any)
const BotLancesConfiguracoesRoute = BotLancesConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => BotLancesRoute,
} as any)
const BotLancesHistoricoRoute = BotLancesHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => BotLancesRoute,
} as any)
const BotLancesMonitoramentoRoute = BotLancesMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => BotLancesRoute,
} as any)
const BotLancesRelatoriosRoute = BotLancesRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => BotLancesRoute,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriasRoute,
} as any)
const CategoriasCategoryIdRoute = CategoriasCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => CategoriasRoute,
} as any)
const ConcorrentesIndexRoute = ConcorrentesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConcorrentesRoute,
} as any)
const ConcorrentesCategoryIdRoute = ConcorrentesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => ConcorrentesRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const Dash2AjudaRoute = Dash2AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => Dash2Route,
} as any)
const PlanosCompararRoute = PlanosCompararRouteImport.update({
  id: '/planos/comparar',
  path: '/planos/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const BotLancesDisputasIndexRoute = BotLancesDisputasIndexRouteImport.update({
  id: '/disputas/',
  path: '/disputas/',
  getParentRoute: () => BotLancesRoute,
} as any)
const BotLancesDisputasDisputeIdRoute =
  BotLancesDisputasDisputeIdRouteImport.update({
    id: '/disputas/$disputeId',
    path: '/disputas/$disputeId',
    getParentRoute: () => BotLancesRoute,
  } as any)
const ConcorrentesCategoryIdCompanyIdRoute =
  ConcorrentesCategoryIdCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => ConcorrentesCategoryIdRoute,
  } as any)
const Dash2ConfiguracoesEmpresaRoute =
  Dash2ConfiguracoesEmpresaRouteImport.update({
    id: '/configuracoes/empresa',
    path: '/configuracoes/empresa',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2ConfiguracoesEquipeRoute =
  Dash2ConfiguracoesEquipeRouteImport.update({
    id: '/configuracoes/equipe',
    path: '/configuracoes/equipe',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2ConfiguracoesNotificacoesRoute =
  Dash2ConfiguracoesNotificacoesRouteImport.update({
    id: '/configuracoes/notificacoes',
    path: '/configuracoes/notificacoes',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2ConfiguracoesPerfilRoute =
  Dash2ConfiguracoesPerfilRouteImport.update({
    id: '/configuracoes/perfil',
    path: '/configuracoes/perfil',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2ConfiguracoesPlanoRoute = Dash2ConfiguracoesPlanoRouteImport.update({
  id: '/configuracoes/plano',
  path: '/configuracoes/plano',
  getParentRoute: () => Dash2Route,
} as any)
const Dash2ConfiguracoesSegurancaRoute =
  Dash2ConfiguracoesSegurancaRouteImport.update({
    id: '/configuracoes/seguranca',
    path: '/configuracoes/seguranca',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2GestaoTemplatesEmailsRoute =
  Dash2GestaoTemplatesEmailsRouteImport.update({
    id: '/gestao/templates-emails',
    path: '/gestao/templates-emails',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2LicitacoesLicitacaoIdRoute =
  Dash2LicitacoesLicitacaoIdRouteImport.update({
    id: '/licitacoes/$licitacaoId',
    path: '/licitacoes/$licitacaoId',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2LicitacoesBuscarRoute = Dash2LicitacoesBuscarRouteImport.update({
  id: '/licitacoes/buscar',
  path: '/licitacoes/buscar',
  getParentRoute: () => Dash2Route,
} as any)
const Dash2LicitacoesFiltrosSalvosRoute =
  Dash2LicitacoesFiltrosSalvosRouteImport.update({
    id: '/licitacoes/filtros-salvos',
    path: '/licitacoes/filtros-salvos',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2OperacaoAnotacoesRoute = Dash2OperacaoAnotacoesRouteImport.update({
  id: '/operacao/anotacoes',
  path: '/operacao/anotacoes',
  getParentRoute: () => Dash2Route,
} as any)
const Dash2OperacaoMinhasLicitacoesRoute =
  Dash2OperacaoMinhasLicitacoesRouteImport.update({
    id: '/operacao/minhas-licitacoes',
    path: '/operacao/minhas-licitacoes',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2OportunidadesFavoritosRoute =
  Dash2OportunidadesFavoritosRouteImport.update({
    id: '/oportunidades/favoritos',
    path: '/oportunidades/favoritos',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2OportunidadesNovasRoute = Dash2OportunidadesNovasRouteImport.update({
  id: '/oportunidades/novas',
  path: '/oportunidades/novas',
  getParentRoute: () => Dash2Route,
} as any)
const CategoriasCategoryIdEstadoStateIdRoute =
  CategoriasCategoryIdEstadoStateIdRouteImport.update({
    id: '/estado/$stateId',
    path: '/estado/$stateId',
    getParentRoute: () => CategoriasCategoryIdRoute,
  } as any)
const Dash2ConfiguracoesFaturasInvoiceIdRoute =
  Dash2ConfiguracoesFaturasInvoiceIdRouteImport.update({
    id: '/configuracoes/faturas/$invoiceId',
    path: '/configuracoes/faturas/$invoiceId',
    getParentRoute: () => Dash2Route,
  } as any)
const Dash2OperacaoMinhasLicitacoesLicitacaoIdRoute =
  Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteImport.update({
    id: '/$licitacaoId',
    path: '/$licitacaoId',
    getParentRoute: () => Dash2OperacaoMinhasLicitacoesRoute,
  } as any)
const Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRoute =
  Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRouteImport.update({
    id: '/disputa',
    path: '/disputa',
    getParentRoute: () => Dash2OperacaoMinhasLicitacoesLicitacaoIdRoute,
  } as any)
const Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRoute =
  Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRouteImport.update({
    id: '/proposta',
    path: '/proposta',
    getParentRoute: () => Dash2OperacaoMinhasLicitacoesLicitacaoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bot-lances': typeof BotLancesRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/concorrentes': typeof ConcorrentesRouteWithChildren
  '/dash2': typeof Dash2RouteWithChildren
  '/documentos': typeof DocumentosRoute
  '/integracoes': typeof IntegracoesRoute
  '/itens': typeof ItensRoute
  '/login': typeof LoginRoute
  '/lp': typeof LpRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/raio-x': typeof RaioXRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/score-orgaos': typeof ScoreOrgaosRoute
  '/bot-lances/configuracoes': typeof BotLancesConfiguracoesRoute
  '/bot-lances/historico': typeof BotLancesHistoricoRoute
  '/bot-lances/monitoramento': typeof BotLancesMonitoramentoRoute
  '/bot-lances/relatorios': typeof BotLancesRelatoriosRoute
  '/categorias/$categoryId': typeof CategoriasCategoryIdRouteWithChildren
  '/concorrentes/$categoryId': typeof ConcorrentesCategoryIdRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/dash2/ajuda': typeof Dash2AjudaRoute
  '/planos/comparar': typeof PlanosCompararRoute
  '/bot-lances/': typeof BotLancesIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/concorrentes/': typeof ConcorrentesIndexRoute
  '/bot-lances/disputas/$disputeId': typeof BotLancesDisputasDisputeIdRoute
  '/concorrentes/$categoryId/$companyId': typeof ConcorrentesCategoryIdCompanyIdRoute
  '/dash2/configuracoes/empresa': typeof Dash2ConfiguracoesEmpresaRoute
  '/dash2/configuracoes/equipe': typeof Dash2ConfiguracoesEquipeRoute
  '/dash2/configuracoes/notificacoes': typeof Dash2ConfiguracoesNotificacoesRoute
  '/dash2/configuracoes/perfil': typeof Dash2ConfiguracoesPerfilRoute
  '/dash2/configuracoes/plano': typeof Dash2ConfiguracoesPlanoRoute
  '/dash2/configuracoes/seguranca': typeof Dash2ConfiguracoesSegurancaRoute
  '/dash2/gestao/templates-emails': typeof Dash2GestaoTemplatesEmailsRoute
  '/dash2/licitacoes/$licitacaoId': typeof Dash2LicitacoesLicitacaoIdRoute
  '/dash2/licitacoes/buscar': typeof Dash2LicitacoesBuscarRoute
  '/dash2/licitacoes/filtros-salvos': typeof Dash2LicitacoesFiltrosSalvosRoute
  '/dash2/operacao/anotacoes': typeof Dash2OperacaoAnotacoesRoute
  '/dash2/operacao/minhas-licitacoes': typeof Dash2OperacaoMinhasLicitacoesRouteWithChildren
  '/dash2/oportunidades/favoritos': typeof Dash2OportunidadesFavoritosRoute
  '/dash2/oportunidades/novas': typeof Dash2OportunidadesNovasRoute
  '/bot-lances/disputas/': typeof BotLancesDisputasIndexRoute
  '/categorias/$categoryId/estado/$stateId': typeof CategoriasCategoryIdEstadoStateIdRoute
  '/dash2/configuracoes/faturas/$invoiceId': typeof Dash2ConfiguracoesFaturasInvoiceIdRoute
  '/dash2/operacao/minhas-licitacoes/$licitacaoId': typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteWithChildren
  '/dash2/operacao/minhas-licitacoes/$licitacaoId/disputa': typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRoute
  '/dash2/operacao/minhas-licitacoes/$licitacaoId/proposta': typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/dash2': typeof Dash2RouteWithChildren
  '/documentos': typeof DocumentosRoute
  '/integracoes': typeof IntegracoesRoute
  '/itens': typeof ItensRoute
  '/login': typeof LoginRoute
  '/lp': typeof LpRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/raio-x': typeof RaioXRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/score-orgaos': typeof ScoreOrgaosRoute
  '/bot-lances/configuracoes': typeof BotLancesConfiguracoesRoute
  '/bot-lances/historico': typeof BotLancesHistoricoRoute
  '/bot-lances/monitoramento': typeof BotLancesMonitoramentoRoute
  '/bot-lances/relatorios': typeof BotLancesRelatoriosRoute
  '/categorias/$categoryId': typeof CategoriasCategoryIdRouteWithChildren
  '/concorrentes/$categoryId': typeof ConcorrentesCategoryIdRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/dash2/ajuda': typeof Dash2AjudaRoute
  '/planos/comparar': typeof PlanosCompararRoute
  '/bot-lances': typeof BotLancesIndexRoute
  '/categorias': typeof CategoriasIndexRoute
  '/concorrentes': typeof ConcorrentesIndexRoute
  '/bot-lances/disputas/$disputeId': typeof BotLancesDisputasDisputeIdRoute
  '/concorrentes/$categoryId/$companyId': typeof ConcorrentesCategoryIdCompanyIdRoute
  '/dash2/configuracoes/empresa': typeof Dash2ConfiguracoesEmpresaRoute
  '/dash2/configuracoes/equipe': typeof Dash2ConfiguracoesEquipeRoute
  '/dash2/configuracoes/notificacoes': typeof Dash2ConfiguracoesNotificacoesRoute
  '/dash2/configuracoes/perfil': typeof Dash2ConfiguracoesPerfilRoute
  '/dash2/configuracoes/plano': typeof Dash2ConfiguracoesPlanoRoute
  '/dash2/configuracoes/seguranca': typeof Dash2ConfiguracoesSegurancaRoute
  '/dash2/gestao/templates-emails': typeof Dash2GestaoTemplatesEmailsRoute
  '/dash2/licitacoes/$licitacaoId': typeof Dash2LicitacoesLicitacaoIdRoute
  '/dash2/licitacoes/buscar': typeof Dash2LicitacoesBuscarRoute
  '/dash2/licitacoes/filtros-salvos': typeof Dash2LicitacoesFiltrosSalvosRoute
  '/dash2/operacao/anotacoes': typeof Dash2OperacaoAnotacoesRoute
  '/dash2/operacao/minhas-licitacoes': typeof Dash2OperacaoMinhasLicitacoesRouteWithChildren
  '/dash2/oportunidades/favoritos': typeof Dash2OportunidadesFavoritosRoute
  '/dash2/oportunidades/novas': typeof Dash2OportunidadesNovasRoute
  '/bot-lances/disputas': typeof BotLancesDisputasIndexRoute
  '/categorias/$categoryId/estado/$stateId': typeof CategoriasCategoryIdEstadoStateIdRoute
  '/dash2/configuracoes/faturas/$invoiceId': typeof Dash2ConfiguracoesFaturasInvoiceIdRoute
  '/dash2/operacao/minhas-licitacoes/$licitacaoId': typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteWithChildren
  '/dash2/operacao/minhas-licitacoes/$licitacaoId/disputa': typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRoute
  '/dash2/operacao/minhas-licitacoes/$licitacaoId/proposta': typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bot-lances': typeof BotLancesRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/concorrentes': typeof ConcorrentesRouteWithChildren
  '/dash2': typeof Dash2RouteWithChildren
  '/documentos': typeof DocumentosRoute
  '/integracoes': typeof IntegracoesRoute
  '/itens': typeof ItensRoute
  '/login': typeof LoginRoute
  '/lp': typeof LpRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/raio-x': typeof RaioXRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/score-orgaos': typeof ScoreOrgaosRoute
  '/bot-lances/configuracoes': typeof BotLancesConfiguracoesRoute
  '/bot-lances/historico': typeof BotLancesHistoricoRoute
  '/bot-lances/monitoramento': typeof BotLancesMonitoramentoRoute
  '/bot-lances/relatorios': typeof BotLancesRelatoriosRoute
  '/categorias/$categoryId': typeof CategoriasCategoryIdRouteWithChildren
  '/concorrentes/$categoryId': typeof ConcorrentesCategoryIdRouteWithChildren
  '/convite/$token': typeof ConviteTokenRoute
  '/dash2/ajuda': typeof Dash2AjudaRoute
  '/planos/comparar': typeof PlanosCompararRoute
  '/bot-lances/': typeof BotLancesIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/concorrentes/': typeof ConcorrentesIndexRoute
  '/bot-lances/disputas/$disputeId': typeof BotLancesDisputasDisputeIdRoute
  '/concorrentes/$categoryId/$companyId': typeof ConcorrentesCategoryIdCompanyIdRoute
  '/dash2/configuracoes/empresa': typeof Dash2ConfiguracoesEmpresaRoute
  '/dash2/configuracoes/equipe': typeof Dash2ConfiguracoesEquipeRoute
  '/dash2/configuracoes/notificacoes': typeof Dash2ConfiguracoesNotificacoesRoute
  '/dash2/configuracoes/perfil': typeof Dash2ConfiguracoesPerfilRoute
  '/dash2/configuracoes/plano': typeof Dash2ConfiguracoesPlanoRoute
  '/dash2/configuracoes/seguranca': typeof Dash2ConfiguracoesSegurancaRoute
  '/dash2/gestao/templates-emails': typeof Dash2GestaoTemplatesEmailsRoute
  '/dash2/licitacoes/$licitacaoId': typeof Dash2LicitacoesLicitacaoIdRoute
  '/dash2/licitacoes/buscar': typeof Dash2LicitacoesBuscarRoute
  '/dash2/licitacoes/filtros-salvos': typeof Dash2LicitacoesFiltrosSalvosRoute
  '/dash2/operacao/anotacoes': typeof Dash2OperacaoAnotacoesRoute
  '/dash2/operacao/minhas-licitacoes': typeof Dash2OperacaoMinhasLicitacoesRouteWithChildren
  '/dash2/oportunidades/favoritos': typeof Dash2OportunidadesFavoritosRoute
  '/dash2/oportunidades/novas': typeof Dash2OportunidadesNovasRoute
  '/bot-lances/disputas/': typeof BotLancesDisputasIndexRoute
  '/categorias/$categoryId/estado/$stateId': typeof CategoriasCategoryIdEstadoStateIdRoute
  '/dash2/configuracoes/faturas/$invoiceId': typeof Dash2ConfiguracoesFaturasInvoiceIdRoute
  '/dash2/operacao/minhas-licitacoes/$licitacaoId': typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteWithChildren
  '/dash2/operacao/minhas-licitacoes/$licitacaoId/disputa': typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRoute
  '/dash2/operacao/minhas-licitacoes/$licitacaoId/proposta': typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bot-lances'
    | '/cadastro'
    | '/categorias'
    | '/concorrentes'
    | '/dash2'
    | '/documentos'
    | '/integracoes'
    | '/itens'
    | '/login'
    | '/lp'
    | '/onboarding'
    | '/pipeline'
    | '/raio-x'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
    | '/score-orgaos'
    | '/bot-lances/configuracoes'
    | '/bot-lances/historico'
    | '/bot-lances/monitoramento'
    | '/bot-lances/relatorios'
    | '/categorias/$categoryId'
    | '/concorrentes/$categoryId'
    | '/convite/$token'
    | '/dash2/ajuda'
    | '/planos/comparar'
    | '/bot-lances/'
    | '/categorias/'
    | '/concorrentes/'
    | '/bot-lances/disputas/$disputeId'
    | '/concorrentes/$categoryId/$companyId'
    | '/dash2/configuracoes/empresa'
    | '/dash2/configuracoes/equipe'
    | '/dash2/configuracoes/notificacoes'
    | '/dash2/configuracoes/perfil'
    | '/dash2/configuracoes/plano'
    | '/dash2/configuracoes/seguranca'
    | '/dash2/gestao/templates-emails'
    | '/dash2/licitacoes/$licitacaoId'
    | '/dash2/licitacoes/buscar'
    | '/dash2/licitacoes/filtros-salvos'
    | '/dash2/operacao/anotacoes'
    | '/dash2/operacao/minhas-licitacoes'
    | '/dash2/oportunidades/favoritos'
    | '/dash2/oportunidades/novas'
    | '/bot-lances/disputas/'
    | '/categorias/$categoryId/estado/$stateId'
    | '/dash2/configuracoes/faturas/$invoiceId'
    | '/dash2/operacao/minhas-licitacoes/$licitacaoId'
    | '/dash2/operacao/minhas-licitacoes/$licitacaoId/disputa'
    | '/dash2/operacao/minhas-licitacoes/$licitacaoId/proposta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/dash2'
    | '/documentos'
    | '/integracoes'
    | '/itens'
    | '/login'
    | '/lp'
    | '/onboarding'
    | '/pipeline'
    | '/raio-x'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
    | '/score-orgaos'
    | '/bot-lances/configuracoes'
    | '/bot-lances/historico'
    | '/bot-lances/monitoramento'
    | '/bot-lances/relatorios'
    | '/categorias/$categoryId'
    | '/concorrentes/$categoryId'
    | '/convite/$token'
    | '/dash2/ajuda'
    | '/planos/comparar'
    | '/bot-lances'
    | '/categorias'
    | '/concorrentes'
    | '/bot-lances/disputas/$disputeId'
    | '/concorrentes/$categoryId/$companyId'
    | '/dash2/configuracoes/empresa'
    | '/dash2/configuracoes/equipe'
    | '/dash2/configuracoes/notificacoes'
    | '/dash2/configuracoes/perfil'
    | '/dash2/configuracoes/plano'
    | '/dash2/configuracoes/seguranca'
    | '/dash2/gestao/templates-emails'
    | '/dash2/licitacoes/$licitacaoId'
    | '/dash2/licitacoes/buscar'
    | '/dash2/licitacoes/filtros-salvos'
    | '/dash2/operacao/anotacoes'
    | '/dash2/operacao/minhas-licitacoes'
    | '/dash2/oportunidades/favoritos'
    | '/dash2/oportunidades/novas'
    | '/bot-lances/disputas'
    | '/categorias/$categoryId/estado/$stateId'
    | '/dash2/configuracoes/faturas/$invoiceId'
    | '/dash2/operacao/minhas-licitacoes/$licitacaoId'
    | '/dash2/operacao/minhas-licitacoes/$licitacaoId/disputa'
    | '/dash2/operacao/minhas-licitacoes/$licitacaoId/proposta'
  id:
    | '__root__'
    | '/'
    | '/bot-lances'
    | '/cadastro'
    | '/categorias'
    | '/concorrentes'
    | '/dash2'
    | '/documentos'
    | '/integracoes'
    | '/itens'
    | '/login'
    | '/lp'
    | '/onboarding'
    | '/pipeline'
    | '/raio-x'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/relatorios'
    | '/score-orgaos'
    | '/bot-lances/configuracoes'
    | '/bot-lances/historico'
    | '/bot-lances/monitoramento'
    | '/bot-lances/relatorios'
    | '/categorias/$categoryId'
    | '/concorrentes/$categoryId'
    | '/convite/$token'
    | '/dash2/ajuda'
    | '/planos/comparar'
    | '/bot-lances/'
    | '/categorias/'
    | '/concorrentes/'
    | '/bot-lances/disputas/$disputeId'
    | '/concorrentes/$categoryId/$companyId'
    | '/dash2/configuracoes/empresa'
    | '/dash2/configuracoes/equipe'
    | '/dash2/configuracoes/notificacoes'
    | '/dash2/configuracoes/perfil'
    | '/dash2/configuracoes/plano'
    | '/dash2/configuracoes/seguranca'
    | '/dash2/gestao/templates-emails'
    | '/dash2/licitacoes/$licitacaoId'
    | '/dash2/licitacoes/buscar'
    | '/dash2/licitacoes/filtros-salvos'
    | '/dash2/operacao/anotacoes'
    | '/dash2/operacao/minhas-licitacoes'
    | '/dash2/oportunidades/favoritos'
    | '/dash2/oportunidades/novas'
    | '/bot-lances/disputas/'
    | '/categorias/$categoryId/estado/$stateId'
    | '/dash2/configuracoes/faturas/$invoiceId'
    | '/dash2/operacao/minhas-licitacoes/$licitacaoId'
    | '/dash2/operacao/minhas-licitacoes/$licitacaoId/disputa'
    | '/dash2/operacao/minhas-licitacoes/$licitacaoId/proposta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotLancesRoute: typeof BotLancesRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
  ConcorrentesRoute: typeof ConcorrentesRouteWithChildren
  Dash2Route: typeof Dash2RouteWithChildren
  DocumentosRoute: typeof DocumentosRoute
  IntegracoesRoute: typeof IntegracoesRoute
  ItensRoute: typeof ItensRoute
  LoginRoute: typeof LoginRoute
  LpRoute: typeof LpRoute
  OnboardingRoute: typeof OnboardingRoute
  PipelineRoute: typeof PipelineRoute
  RaioXRoute: typeof RaioXRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ScoreOrgaosRoute: typeof ScoreOrgaosRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  PlanosCompararRoute: typeof PlanosCompararRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-lances': {
      id: '/bot-lances'
      path: '/bot-lances'
      fullPath: '/bot-lances'
      preLoaderRoute: typeof BotLancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concorrentes': {
      id: '/concorrentes'
      path: '/concorrentes'
      fullPath: '/concorrentes'
      preLoaderRoute: typeof ConcorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash2': {
      id: '/dash2'
      path: '/dash2'
      fullPath: '/dash2'
      preLoaderRoute: typeof Dash2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itens': {
      id: '/itens'
      path: '/itens'
      fullPath: '/itens'
      preLoaderRoute: typeof ItensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp': {
      id: '/lp'
      path: '/lp'
      fullPath: '/lp'
      preLoaderRoute: typeof LpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raio-x': {
      id: '/raio-x'
      path: '/raio-x'
      fullPath: '/raio-x'
      preLoaderRoute: typeof RaioXRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-orgaos': {
      id: '/score-orgaos'
      path: '/score-orgaos'
      fullPath: '/score-orgaos'
      preLoaderRoute: typeof ScoreOrgaosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-lances/': {
      id: '/bot-lances/'
      path: '/'
      fullPath: '/bot-lances/'
      preLoaderRoute: typeof BotLancesIndexRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/bot-lances/configuracoes': {
      id: '/bot-lances/configuracoes'
      path: '/configuracoes'
      fullPath: '/bot-lances/configuracoes'
      preLoaderRoute: typeof BotLancesConfiguracoesRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/bot-lances/historico': {
      id: '/bot-lances/historico'
      path: '/historico'
      fullPath: '/bot-lances/historico'
      preLoaderRoute: typeof BotLancesHistoricoRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/bot-lances/monitoramento': {
      id: '/bot-lances/monitoramento'
      path: '/monitoramento'
      fullPath: '/bot-lances/monitoramento'
      preLoaderRoute: typeof BotLancesMonitoramentoRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/bot-lances/relatorios': {
      id: '/bot-lances/relatorios'
      path: '/relatorios'
      fullPath: '/bot-lances/relatorios'
      preLoaderRoute: typeof BotLancesRelatoriosRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/categorias/$categoryId': {
      id: '/categorias/$categoryId'
      path: '/$categoryId'
      fullPath: '/categorias/$categoryId'
      preLoaderRoute: typeof CategoriasCategoryIdRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/concorrentes/': {
      id: '/concorrentes/'
      path: '/'
      fullPath: '/concorrentes/'
      preLoaderRoute: typeof ConcorrentesIndexRouteImport
      parentRoute: typeof ConcorrentesRoute
    }
    '/concorrentes/$categoryId': {
      id: '/concorrentes/$categoryId'
      path: '/$categoryId'
      fullPath: '/concorrentes/$categoryId'
      preLoaderRoute: typeof ConcorrentesCategoryIdRouteImport
      parentRoute: typeof ConcorrentesRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash2/ajuda': {
      id: '/dash2/ajuda'
      path: '/ajuda'
      fullPath: '/dash2/ajuda'
      preLoaderRoute: typeof Dash2AjudaRouteImport
      parentRoute: typeof Dash2Route
    }
    '/planos/comparar': {
      id: '/planos/comparar'
      path: '/planos/comparar'
      fullPath: '/planos/comparar'
      preLoaderRoute: typeof PlanosCompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-lances/disputas/': {
      id: '/bot-lances/disputas/'
      path: '/disputas'
      fullPath: '/bot-lances/disputas/'
      preLoaderRoute: typeof BotLancesDisputasIndexRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/bot-lances/disputas/$disputeId': {
      id: '/bot-lances/disputas/$disputeId'
      path: '/disputas/$disputeId'
      fullPath: '/bot-lances/disputas/$disputeId'
      preLoaderRoute: typeof BotLancesDisputasDisputeIdRouteImport
      parentRoute: typeof BotLancesRoute
    }
    '/concorrentes/$categoryId/$companyId': {
      id: '/concorrentes/$categoryId/$companyId'
      path: '/$companyId'
      fullPath: '/concorrentes/$categoryId/$companyId'
      preLoaderRoute: typeof ConcorrentesCategoryIdCompanyIdRouteImport
      parentRoute: typeof ConcorrentesCategoryIdRoute
    }
    '/dash2/configuracoes/empresa': {
      id: '/dash2/configuracoes/empresa'
      path: '/configuracoes/empresa'
      fullPath: '/dash2/configuracoes/empresa'
      preLoaderRoute: typeof Dash2ConfiguracoesEmpresaRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/configuracoes/equipe': {
      id: '/dash2/configuracoes/equipe'
      path: '/configuracoes/equipe'
      fullPath: '/dash2/configuracoes/equipe'
      preLoaderRoute: typeof Dash2ConfiguracoesEquipeRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/configuracoes/notificacoes': {
      id: '/dash2/configuracoes/notificacoes'
      path: '/configuracoes/notificacoes'
      fullPath: '/dash2/configuracoes/notificacoes'
      preLoaderRoute: typeof Dash2ConfiguracoesNotificacoesRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/configuracoes/perfil': {
      id: '/dash2/configuracoes/perfil'
      path: '/configuracoes/perfil'
      fullPath: '/dash2/configuracoes/perfil'
      preLoaderRoute: typeof Dash2ConfiguracoesPerfilRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/configuracoes/plano': {
      id: '/dash2/configuracoes/plano'
      path: '/configuracoes/plano'
      fullPath: '/dash2/configuracoes/plano'
      preLoaderRoute: typeof Dash2ConfiguracoesPlanoRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/configuracoes/seguranca': {
      id: '/dash2/configuracoes/seguranca'
      path: '/configuracoes/seguranca'
      fullPath: '/dash2/configuracoes/seguranca'
      preLoaderRoute: typeof Dash2ConfiguracoesSegurancaRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/gestao/templates-emails': {
      id: '/dash2/gestao/templates-emails'
      path: '/gestao/templates-emails'
      fullPath: '/dash2/gestao/templates-emails'
      preLoaderRoute: typeof Dash2GestaoTemplatesEmailsRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/licitacoes/$licitacaoId': {
      id: '/dash2/licitacoes/$licitacaoId'
      path: '/licitacoes/$licitacaoId'
      fullPath: '/dash2/licitacoes/$licitacaoId'
      preLoaderRoute: typeof Dash2LicitacoesLicitacaoIdRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/licitacoes/buscar': {
      id: '/dash2/licitacoes/buscar'
      path: '/licitacoes/buscar'
      fullPath: '/dash2/licitacoes/buscar'
      preLoaderRoute: typeof Dash2LicitacoesBuscarRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/licitacoes/filtros-salvos': {
      id: '/dash2/licitacoes/filtros-salvos'
      path: '/licitacoes/filtros-salvos'
      fullPath: '/dash2/licitacoes/filtros-salvos'
      preLoaderRoute: typeof Dash2LicitacoesFiltrosSalvosRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/operacao/anotacoes': {
      id: '/dash2/operacao/anotacoes'
      path: '/operacao/anotacoes'
      fullPath: '/dash2/operacao/anotacoes'
      preLoaderRoute: typeof Dash2OperacaoAnotacoesRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/operacao/minhas-licitacoes': {
      id: '/dash2/operacao/minhas-licitacoes'
      path: '/operacao/minhas-licitacoes'
      fullPath: '/dash2/operacao/minhas-licitacoes'
      preLoaderRoute: typeof Dash2OperacaoMinhasLicitacoesRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/oportunidades/favoritos': {
      id: '/dash2/oportunidades/favoritos'
      path: '/oportunidades/favoritos'
      fullPath: '/dash2/oportunidades/favoritos'
      preLoaderRoute: typeof Dash2OportunidadesFavoritosRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/oportunidades/novas': {
      id: '/dash2/oportunidades/novas'
      path: '/oportunidades/novas'
      fullPath: '/dash2/oportunidades/novas'
      preLoaderRoute: typeof Dash2OportunidadesNovasRouteImport
      parentRoute: typeof Dash2Route
    }
    '/categorias/$categoryId/estado/$stateId': {
      id: '/categorias/$categoryId/estado/$stateId'
      path: '/estado/$stateId'
      fullPath: '/categorias/$categoryId/estado/$stateId'
      preLoaderRoute: typeof CategoriasCategoryIdEstadoStateIdRouteImport
      parentRoute: typeof CategoriasCategoryIdRoute
    }
    '/dash2/configuracoes/faturas/$invoiceId': {
      id: '/dash2/configuracoes/faturas/$invoiceId'
      path: '/configuracoes/faturas/$invoiceId'
      fullPath: '/dash2/configuracoes/faturas/$invoiceId'
      preLoaderRoute: typeof Dash2ConfiguracoesFaturasInvoiceIdRouteImport
      parentRoute: typeof Dash2Route
    }
    '/dash2/operacao/minhas-licitacoes/$licitacaoId': {
      id: '/dash2/operacao/minhas-licitacoes/$licitacaoId'
      path: '/$licitacaoId'
      fullPath: '/dash2/operacao/minhas-licitacoes/$licitacaoId'
      preLoaderRoute: typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteImport
      parentRoute: typeof Dash2OperacaoMinhasLicitacoesRoute
    }
    '/dash2/operacao/minhas-licitacoes/$licitacaoId/disputa': {
      id: '/dash2/operacao/minhas-licitacoes/$licitacaoId/disputa'
      path: '/disputa'
      fullPath: '/dash2/operacao/minhas-licitacoes/$licitacaoId/disputa'
      preLoaderRoute: typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRouteImport
      parentRoute: typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdRoute
    }
    '/dash2/operacao/minhas-licitacoes/$licitacaoId/proposta': {
      id: '/dash2/operacao/minhas-licitacoes/$licitacaoId/proposta'
      path: '/proposta'
      fullPath: '/dash2/operacao/minhas-licitacoes/$licitacaoId/proposta'
      preLoaderRoute: typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRouteImport
      parentRoute: typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdRoute
    }
  }
}

interface BotLancesRouteChildren {
  BotLancesConfiguracoesRoute: typeof BotLancesConfiguracoesRoute
  BotLancesHistoricoRoute: typeof BotLancesHistoricoRoute
  BotLancesMonitoramentoRoute: typeof BotLancesMonitoramentoRoute
  BotLancesRelatoriosRoute: typeof BotLancesRelatoriosRoute
  BotLancesIndexRoute: typeof BotLancesIndexRoute
  BotLancesDisputasDisputeIdRoute: typeof BotLancesDisputasDisputeIdRoute
  BotLancesDisputasIndexRoute: typeof BotLancesDisputasIndexRoute
}

const BotLancesRouteChildren: BotLancesRouteChildren = {
  BotLancesConfiguracoesRoute: BotLancesConfiguracoesRoute,
  BotLancesHistoricoRoute: BotLancesHistoricoRoute,
  BotLancesMonitoramentoRoute: BotLancesMonitoramentoRoute,
  BotLancesRelatoriosRoute: BotLancesRelatoriosRoute,
  BotLancesIndexRoute: BotLancesIndexRoute,
  BotLancesDisputasDisputeIdRoute: BotLancesDisputasDisputeIdRoute,
  BotLancesDisputasIndexRoute: BotLancesDisputasIndexRoute,
}

const BotLancesRouteWithChildren = BotLancesRoute._addFileChildren(
  BotLancesRouteChildren,
)

interface CategoriasCategoryIdRouteChildren {
  CategoriasCategoryIdEstadoStateIdRoute: typeof CategoriasCategoryIdEstadoStateIdRoute
}

const CategoriasCategoryIdRouteChildren: CategoriasCategoryIdRouteChildren = {
  CategoriasCategoryIdEstadoStateIdRoute:
    CategoriasCategoryIdEstadoStateIdRoute,
}

const CategoriasCategoryIdRouteWithChildren =
  CategoriasCategoryIdRoute._addFileChildren(CategoriasCategoryIdRouteChildren)

interface CategoriasRouteChildren {
  CategoriasCategoryIdRoute: typeof CategoriasCategoryIdRouteWithChildren
  CategoriasIndexRoute: typeof CategoriasIndexRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasCategoryIdRoute: CategoriasCategoryIdRouteWithChildren,
  CategoriasIndexRoute: CategoriasIndexRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

interface ConcorrentesCategoryIdRouteChildren {
  ConcorrentesCategoryIdCompanyIdRoute: typeof ConcorrentesCategoryIdCompanyIdRoute
}

const ConcorrentesCategoryIdRouteChildren: ConcorrentesCategoryIdRouteChildren =
  {
    ConcorrentesCategoryIdCompanyIdRoute: ConcorrentesCategoryIdCompanyIdRoute,
  }

const ConcorrentesCategoryIdRouteWithChildren =
  ConcorrentesCategoryIdRoute._addFileChildren(
    ConcorrentesCategoryIdRouteChildren,
  )

interface ConcorrentesRouteChildren {
  ConcorrentesCategoryIdRoute: typeof ConcorrentesCategoryIdRouteWithChildren
  ConcorrentesIndexRoute: typeof ConcorrentesIndexRoute
}

const ConcorrentesRouteChildren: ConcorrentesRouteChildren = {
  ConcorrentesCategoryIdRoute: ConcorrentesCategoryIdRouteWithChildren,
  ConcorrentesIndexRoute: ConcorrentesIndexRoute,
}

const ConcorrentesRouteWithChildren = ConcorrentesRoute._addFileChildren(
  ConcorrentesRouteChildren,
)

interface Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteChildren {
  Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRoute: typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRoute
  Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRoute: typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRoute
}

const Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteChildren: Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteChildren =
  {
    Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRoute:
      Dash2OperacaoMinhasLicitacoesLicitacaoIdDisputaRoute,
    Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRoute:
      Dash2OperacaoMinhasLicitacoesLicitacaoIdPropostaRoute,
  }

const Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteWithChildren =
  Dash2OperacaoMinhasLicitacoesLicitacaoIdRoute._addFileChildren(
    Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteChildren,
  )

interface Dash2OperacaoMinhasLicitacoesRouteChildren {
  Dash2OperacaoMinhasLicitacoesLicitacaoIdRoute: typeof Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteWithChildren
}

const Dash2OperacaoMinhasLicitacoesRouteChildren: Dash2OperacaoMinhasLicitacoesRouteChildren =
  {
    Dash2OperacaoMinhasLicitacoesLicitacaoIdRoute:
      Dash2OperacaoMinhasLicitacoesLicitacaoIdRouteWithChildren,
  }

const Dash2OperacaoMinhasLicitacoesRouteWithChildren =
  Dash2OperacaoMinhasLicitacoesRoute._addFileChildren(
    Dash2OperacaoMinhasLicitacoesRouteChildren,
  )

interface Dash2RouteChildren {
  Dash2AjudaRoute: typeof Dash2AjudaRoute
  Dash2ConfiguracoesEmpresaRoute: typeof Dash2ConfiguracoesEmpresaRoute
  Dash2ConfiguracoesEquipeRoute: typeof Dash2ConfiguracoesEquipeRoute
  Dash2ConfiguracoesNotificacoesRoute: typeof Dash2ConfiguracoesNotificacoesRoute
  Dash2ConfiguracoesPerfilRoute: typeof Dash2ConfiguracoesPerfilRoute
  Dash2ConfiguracoesPlanoRoute: typeof Dash2ConfiguracoesPlanoRoute
  Dash2ConfiguracoesSegurancaRoute: typeof Dash2ConfiguracoesSegurancaRoute
  Dash2GestaoTemplatesEmailsRoute: typeof Dash2GestaoTemplatesEmailsRoute
  Dash2LicitacoesLicitacaoIdRoute: typeof Dash2LicitacoesLicitacaoIdRoute
  Dash2LicitacoesBuscarRoute: typeof Dash2LicitacoesBuscarRoute
  Dash2LicitacoesFiltrosSalvosRoute: typeof Dash2LicitacoesFiltrosSalvosRoute
  Dash2OperacaoAnotacoesRoute: typeof Dash2OperacaoAnotacoesRoute
  Dash2OperacaoMinhasLicitacoesRoute: typeof Dash2OperacaoMinhasLicitacoesRouteWithChildren
  Dash2OportunidadesFavoritosRoute: typeof Dash2OportunidadesFavoritosRoute
  Dash2OportunidadesNovasRoute: typeof Dash2OportunidadesNovasRoute
  Dash2ConfiguracoesFaturasInvoiceIdRoute: typeof Dash2ConfiguracoesFaturasInvoiceIdRoute
}

const Dash2RouteChildren: Dash2RouteChildren = {
  Dash2AjudaRoute: Dash2AjudaRoute,
  Dash2ConfiguracoesEmpresaRoute: Dash2ConfiguracoesEmpresaRoute,
  Dash2ConfiguracoesEquipeRoute: Dash2ConfiguracoesEquipeRoute,
  Dash2ConfiguracoesNotificacoesRoute: Dash2ConfiguracoesNotificacoesRoute,
  Dash2ConfiguracoesPerfilRoute: Dash2ConfiguracoesPerfilRoute,
  Dash2ConfiguracoesPlanoRoute: Dash2ConfiguracoesPlanoRoute,
  Dash2ConfiguracoesSegurancaRoute: Dash2ConfiguracoesSegurancaRoute,
  Dash2GestaoTemplatesEmailsRoute: Dash2GestaoTemplatesEmailsRoute,
  Dash2LicitacoesLicitacaoIdRoute: Dash2LicitacoesLicitacaoIdRoute,
  Dash2LicitacoesBuscarRoute: Dash2LicitacoesBuscarRoute,
  Dash2LicitacoesFiltrosSalvosRoute: Dash2LicitacoesFiltrosSalvosRoute,
  Dash2OperacaoAnotacoesRoute: Dash2OperacaoAnotacoesRoute,
  Dash2OperacaoMinhasLicitacoesRoute:
    Dash2OperacaoMinhasLicitacoesRouteWithChildren,
  Dash2OportunidadesFavoritosRoute: Dash2OportunidadesFavoritosRoute,
  Dash2OportunidadesNovasRoute: Dash2OportunidadesNovasRoute,
  Dash2ConfiguracoesFaturasInvoiceIdRoute:
    Dash2ConfiguracoesFaturasInvoiceIdRoute,
}

const Dash2RouteWithChildren = Dash2Route._addFileChildren(Dash2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotLancesRoute: BotLancesRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
  ConcorrentesRoute: ConcorrentesRouteWithChildren,
  Dash2Route: Dash2RouteWithChildren,
  DocumentosRoute: DocumentosRoute,
  IntegracoesRoute: IntegracoesRoute,
  ItensRoute: ItensRoute,
  LoginRoute: LoginRoute,
  LpRoute: LpRoute,
  OnboardingRoute: OnboardingRoute,
  PipelineRoute: PipelineRoute,
  RaioXRoute: RaioXRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  ScoreOrgaosRoute: ScoreOrgaosRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  PlanosCompararRoute: PlanosCompararRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
